/**
 * Full exercise options for benchmarks — used for "Add exercise" dropdown per section.
 * Each section has hundreds of options so users can add any exercise they track.
 */

export type BenchmarkOption = { key: string; label: string; unit?: string };

/** Strength (1RM kg) — compound and isolation exercises */
export const STRENGTH_OPTIONS: BenchmarkOption[] = [
  // Squat pattern
  { key: "back_squat", label: "Back Squat" },
  { key: "front_squat", label: "Front Squat" },
  { key: "overhead_squat", label: "Overhead Squat" },
  { key: "safety_bar_squat", label: "Safety Bar Squat" },
  { key: "box_squat", label: "Box Squat" },
  { key: "pause_squat", label: "Pause Squat" },
  { key: "goblet_squat", label: "Goblet Squat" },
  { key: "belt_squat", label: "Belt Squat" },
  { key: "hack_squat", label: "Hack Squat" },
  { key: "leg_press", label: "Leg Press" },
  { key: "split_squat", label: "Rear-Foot Elevated Split Squat" },
  { key: "bulgarian_split_squat", label: "Bulgarian Split Squat" },
  { key: "lunge", label: "Walking Lunge" },
  { key: "lateral_lunge", label: "Lateral Lunge" },
  { key: "step_up", label: "Step-Up" },
  { key: "single_leg_squat", label: "Single Leg Squat" },
  { key: "sissy_squat", label: "Sissy Squat" },
  // Hip hinge
  { key: "deadlift", label: "Deadlift" },
  { key: "trap_bar_deadlift", label: "Trap Bar Deadlift" },
  { key: "rdl", label: "Romanian Deadlift" },
  { key: "db_rdl", label: "Dumbbell RDL" },
  { key: "stiff_leg_deadlift", label: "Stiff Leg Deadlift" },
  { key: "deficit_deadlift", label: "Deficit Deadlift" },
  { key: "snatch_grip_deadlift", label: "Snatch Grip Deadlift" },
  { key: "good_morning", label: "Good Morning" },
  { key: "hip_thrust", label: "Hip Thrust" },
  { key: "glute_bridge", label: "Glute Bridge" },
  { key: "single_leg_hip_thrust", label: "Single Leg Hip Thrust" },
  { key: "kettlebell_swing", label: "Kettlebell Swing" },
  // Horizontal push
  { key: "bench_press", label: "Bench Press" },
  { key: "incline_bench_press", label: "Incline Bench Press" },
  { key: "decline_bench_press", label: "Decline Bench Press" },
  { key: "close_grip_bench", label: "Close Grip Bench Press" },
  { key: "floor_press", label: "Floor Press" },
  { key: "db_press", label: "Dumbbell Press" },
  { key: "db_incline_press", label: "Dumbbell Incline Press" },
  { key: "db_decline_press", label: "Dumbbell Decline Press" },
  { key: "push_up", label: "Push-Up" },
  { key: "dip", label: "Weighted Dip" },
  { key: "chest_fly", label: "Cable/Dumbbell Fly" },
  { key: "pec_deck", label: "Pec Deck" },
  { key: "machine_chest_press", label: "Machine Chest Press" },
  { key: "landmine_press", label: "Landmine Press" },
  // Vertical push
  { key: "overhead_press", label: "Overhead Press" },
  { key: "push_press", label: "Push Press" },
  { key: "strict_press", label: "Strict Press" },
  { key: "db_shoulder_press", label: "Dumbbell Shoulder Press" },
  { key: "arnold_press", label: "Arnold Press" },
  { key: "seated_ohp", label: "Seated Overhead Press" },
  { key: "landmine_ohp", label: "Landmine OHP" },
  { key: "machine_ohp", label: "Machine Shoulder Press" },
  { key: "lateral_raise", label: "Lateral Raise" },
  { key: "front_raise", label: "Front Raise" },
  { key: "reverse_fly", label: "Reverse Fly" },
  { key: "face_pull", label: "Face Pull" },
  { key: "upright_row", label: "Upright Row" },
  // Horizontal pull
  { key: "barbell_row", label: "Barbell Row" },
  { key: "db_row", label: "Dumbbell Row" },
  { key: "t_bar_row", label: "T-Bar Row" },
  { key: "chest_supported_row", label: "Chest Supported Row" },
  { key: "cable_row", label: "Cable Row" },
  { key: "inverted_row", label: "Inverted Row" },
  { key: "landmine_row", label: "Landmine Row" },
  { key: "single_arm_row", label: "Single Arm Row" },
  { key: "pendlay_row", label: "Pendlay Row" },
  { key: "yates_row", label: "Yates Row" },
  // Vertical pull
  { key: "weighted_pullup", label: "Weighted Pull-Up" },
  { key: "chin_up", label: "Chin-Up" },
  { key: "neutral_pullup", label: "Neutral Grip Pull-Up" },
  { key: "lat_pulldown", label: "Lat Pulldown" },
  { key: "close_grip_pulldown", label: "Close Grip Pulldown" },
  { key: "straight_arm_pulldown", label: "Straight Arm Pulldown" },
  { key: "assisted_pullup", label: "Assisted Pull-Up" },
  // Olympic & power
  { key: "power_clean", label: "Power Clean" },
  { key: "clean_and_jerk", label: "Clean & Jerk" },
  { key: "snatch", label: "Snatch" },
  { key: "hang_clean", label: "Hang Clean" },
  { key: "hang_snatch", label: "Hang Snatch" },
  { key: "clean_pull", label: "Clean Pull" },
  { key: "snatch_pull", label: "Snatch Pull" },
  { key: "push_jerk", label: "Push Jerk" },
  { key: "split_jerk", label: "Split Jerk" },
  // Leg isolation
  { key: "leg_curl", label: "Leg Curl" },
  { key: "leg_extension", label: "Leg Extension" },
  { key: "standing_leg_curl", label: "Standing Leg Curl" },
  { key: "seated_leg_curl", label: "Seated Leg Curl" },
  { key: "nordic_curl", label: "Nordic Curl" },
  { key: "hip_abduction", label: "Hip Abduction" },
  { key: "hip_adduction", label: "Hip Adduction" },
  { key: "calf_raise", label: "Calf Raise" },
  { key: "seated_calf_raise", label: "Seated Calf Raise" },
  // Arms & misc
  { key: "barbell_curl", label: "Barbell Curl" },
  { key: "db_curl", label: "Dumbbell Curl" },
  { key: "hammer_curl", label: "Hammer Curl" },
  { key: "preacher_curl", label: "Preacher Curl" },
  { key: "cable_curl", label: "Cable Curl" },
  { key: "tricep_pushdown", label: "Tricep Pushdown" },
  { key: "skull_crusher", label: "Skull Crusher" },
  { key: "tricep_extension", label: "Tricep Extension" },
  { key: "overhead_tricep", label: "Overhead Tricep Extension" },
  { key: "close_grip_pushup", label: "Close Grip Push-Up" },
  { key: "wrist_curl", label: "Wrist Curl" },
  { key: "reverse_wrist_curl", label: "Reverse Wrist Curl" },
  { key: "farmer_carry", label: "Farmer Carry" },
  { key: "suitcase_carry", label: "Suitcase Carry" },
  // Kettlebell
  { key: "kb_goblet_squat", label: "KB Goblet Squat" },
  { key: "kb_clean", label: "Kettlebell Clean" },
  { key: "kb_press", label: "Kettlebell Press" },
  { key: "kb_snatch", label: "Kettlebell Snatch" },
  { key: "kb_tgu", label: "Turkish Get-Up" },
  // More variants (expand to 200+)
  { key: "zercher_squat", label: "Zercher Squat" },
  { key: "jefferson_deadlift", label: "Jefferson Deadlift" },
  { key: "sumo_deadlift", label: "Sumo Deadlift" },
  { key: "conventional_deadlift", label: "Conventional Deadlift" },
  { key: "pin_squat", label: "Pin Squat" },
  { key: "v_squat", label: "V-Squat" },
  { key: "pistol_squat", label: "Pistol Squat" },
  { key: "cossack_squat", label: "Cossack Squat" },
  { key: "squat_jump", label: "Squat Jump (loaded)" },
  { key: "board_press", label: "Board Press" },
  { key: "spoto_press", label: "Spoto Press" },
  { key: "jm_press", label: "JM Press" },
  { key: "bradford_press", label: "Bradford Press" },
  { key: "behind_neck_press", label: "Behind Neck Press" },
  { key: "cuban_press", label: "Cuban Press" },
  { key: "bent_over_lateral", label: "Bent Over Lateral Raise" },
  { key: "pull_up_wide", label: "Wide Grip Pull-Up" },
  { key: "pull_up_close", label: "Close Grip Pull-Up" },
  { key: "commando_pullup", label: "Commando Pull-Up" },
  { key: "muscle_up", label: "Muscle-Up" },
  { key: "front_raise_cable", label: "Cable Front Raise" },
  { key: "shrug", label: "Barbell Shrug" },
  { key: "db_shrug", label: "Dumbbell Shrug" },
  { key: "rack_pull", label: "Rack Pull" },
  { key: "block_pull", label: "Block Pull" },
  { key: "romanian_deadlift_single", label: "Single Leg RDL" },
  { key: "back_extension", label: "Back Extension" },
  { key: "reverse_hyper", label: "Reverse Hyper" },
  { key: "ghr", label: "Glute Ham Raise" },
  { key: "ab_wheel", label: "Ab Wheel" },
  { key: "pallof_press", label: "Pallof Press" },
  { key: "dead_bug", label: "Dead Bug" },
  { key: "hanging_leg_raise", label: "Hanging Leg Raise" },
  { key: "plank", label: "Plank" },
  { key: "dragon_flag", label: "Dragon Flag" },
  { key: "squat_clean", label: "Squat Clean" },
  { key: "power_snatch", label: "Power Snatch" },
  { key: "squat_snatch", label: "Squat Snatch" },
  { key: "one_arm_row", label: "One Arm Row" },
  { key: "meadows_row", label: "Meadows Row" },
  { key: "machine_row", label: "Machine Row" },
  { key: "chest_press_machine", label: "Machine Chest Press" },
  { key: "smith_bench", label: "Smith Machine Bench" },
  { key: "smith_squat", label: "Smith Machine Squat" },
  { key: "smith_ohp", label: "Smith Machine OHP" },
  { key: "cable_fly_high", label: "High Cable Fly" },
  { key: "cable_fly_low", label: "Low Cable Fly" },
  { key: "crossover", label: "Cable Crossover" },
  { key: "concentration_curl", label: "Concentration Curl" },
  { key: "spider_curl", label: "Spider Curl" },
  { key: "ez_bar_curl", label: "EZ Bar Curl" },
  { key: "reverse_curl", label: "Reverse Curl" },
  { key: "lying_tricep", label: "Lying Tricep Extension" },
  { key: "diamond_pushup", label: "Diamond Push-Up" },
  { key: "bench_dip", label: "Bench Dip" },
  { key: "pullover", label: "Pullover" },
  { key: "lat_pull_single", label: "Single Arm Lat Pulldown" },
  { key: "neutral_lat_pull", label: "Neutral Lat Pulldown" },
  { key: "reverse_grip_pulldown", label: "Reverse Grip Pulldown" },
  { key: "wide_lat_pull", label: "Wide Grip Lat Pulldown" },
  { key: "leg_press_single", label: "Single Leg Press" },
  { key: "hack_squat_narrow", label: "Narrow Hack Squat" },
  { key: "v_squat_wide", label: "Wide V-Squat" },
  { key: "curtsy_lunge", label: "Curtsy Lunge" },
  { key: "reverse_lunge", label: "Reverse Lunge" },
  { key: "deficit_reverse_lunge", label: "Deficit Reverse Lunge" },
  { key: "rdl_single_leg", label: "Single Leg RDL" },
  { key: "back_squat_high_bar", label: "High Bar Back Squat" },
  { key: "back_squat_low_bar", label: "Low Bar Back Squat" },
  { key: "front_rack_lunge", label: "Front Rack Lunge" },
  { key: "sldl", label: "Stiff Leg Deadlift" },
  { key: "sumo_rdl", label: "Sumo RDL" },
  { key: "snatch_balance", label: "Snatch Balance" },
  { key: "heaving_snatch", label: "Heaving Snatch Balance" },
  { key: "drop_snatch", label: "Drop Snatch" },
  { key: "push_press_behind", label: "Behind Neck Push Press" },
  { key: "btn_snatch_grip", label: "BTN Snatch Grip Press" },
  { key: "z_press", label: "Z-Press" },
  { key: "seated_good_morning", label: "Seated Good Morning" },
  { key: "good_morning_safety_bar", label: "Safety Bar Good Morning" },
  { key: "belt_squat_leg", label: "Belt Squat (single leg)" },
  { key: "sissy_squat_weighted", label: "Weighted Sissy Squat" },
  { key: "leg_extension_single", label: "Single Leg Extension" },
  { key: "leg_curl_standing_single", label: "Standing Single Leg Curl" },
  { key: "glute_kickback", label: "Glute Kickback" },
  { key: "hip_abduction_seated", label: "Seated Hip Abduction" },
  { key: "hip_abduction_standing", label: "Standing Hip Abduction" },
  { key: "donkey_kick", label: "Donkey Kick" },
  { key: "calf_raise_leg_press", label: "Leg Press Calf Raise" },
  { key: "donkey_calf_raise", label: "Donkey Calf Raise" },
  { key: "tibia_raise", label: "Tibia Raise" },
  { key: "bicep_curl_cable", label: "Cable Bicep Curl" },
  { key: "inceline_db_curl", label: "Incline Dumbbell Curl" },
  { key: "reverse_pec_deck", label: "Reverse Pec Deck" },
  { key: "scaption", label: "Scaption" },
  { key: "prone_y_raise", label: "Prone Y-Raise" },
  { key: "external_rotation", label: "External Rotation" },
  { key: "internal_rotation", label: "Internal Rotation" },
  { key: "cuban_rotation", label: "Cuban Rotation" },
  { key: "bottoms_up_kb_press", label: "Bottoms Up KB Press" },
  { key: "kb_floor_press", label: "KB Floor Press" },
  { key: "db_pullover", label: "Dumbbell Pullover" },
  { key: "straight_arm_pulldown_db", label: "Straight Arm DB Pullover" },
  { key: "renegade_row", label: "Renegade Row" },
  { key: "single_arm_landmine", label: "Single Arm Landmine Row" },
  { key: "chest_supported_incline", label: "Incline Chest Supported Row" },
  { key: "seal_row", label: "Seal Row" },
  { key: "ring_row", label: "Ring Row" },
  { key: "trx_row", label: "TRX Row" },
  { key: "bodyweight_row", label: "Bodyweight Row" },
  { key: "australian_pullup", label: "Australian Pull-Up" },
  { key: "archer_pullup", label: "Archer Pull-Up" },
  { key: "typewriter_pullup", label: "Typewriter Pull-Up" },
  { key: "weighted_chinup", label: "Weighted Chin-Up" },
  { key: "assisted_chinup", label: "Assisted Chin-Up" },
  { key: "neutral_dip", label: "Neutral Grip Dip" },
  { key: "ring_dip", label: "Ring Dip" },
  { key: "bench_press_single_arm", label: "Single Arm Bench Press" },
  { key: "db_floor_press", label: "Dumbbell Floor Press" },
  { key: "db_pullover_chest", label: "DB Pullover (chest)" },
  { key: "cable_crossover_high", label: "High Cable Crossover" },
  { key: "cable_crossover_low", label: "Low Cable Crossover" },
  { key: "pec_fly_machine", label: "Pec Fly Machine" },
  { key: "incline_db_fly", label: "Incline Dumbbell Fly" },
  { key: "decline_db_fly", label: "Decline Dumbbell Fly" },
  { key: "push_up_weighted", label: "Weighted Push-Up" },
  { key: "deficit_push_up", label: "Deficit Push-Up" },
  { key: "ring_push_up", label: "Ring Push-Up" },
  { key: "sphinx_push_up", label: "Sphinx Push-Up" },
  { key: "pike_push_up", label: "Pike Push-Up" },
  { key: "handstand_push_up", label: "Handstand Push-Up" },
  { key: "wall_walk", label: "Wall Walk" },
  { key: "db_z_press", label: "Dumbbell Z-Press" },
  { key: "kettlebell_press_seated", label: "Seated KB Press" },
  { key: "double_kb_press", label: "Double KB Press" },
  { key: "double_kb_front_squat", label: "Double KB Front Squat" },
  { key: "suitcase_deadlift", label: "Suitcase Deadlift" },
  { key: "sandbag_carry", label: "Sandbag Carry" },
  { key: "sandbag_shoulder", label: "Sandbag Shoulder" },
  { key: "yoke_walk", label: "Yoke Walk" },
  { key: "sled_push", label: "Sled Push" },
  { key: "sled_pull", label: "Sled Pull" },
  { key: "trap_bar_shrug", label: "Trap Bar Shrug" },
  { key: "rack_pull_high", label: "High Rack Pull" },
  { key: "block_pull_sumo", label: "Sumo Block Pull" },
  { key: "straddle_lift", label: "Straddle Lift" },
  { key: "suitcase_squat", label: "Suitcase Squat" },
  { key: "goblet_step_up", label: "Goblet Step-Up" },
  { key: "bulgarian_rdl", label: "Bulgarian RDL" },
  { key: "kb_sumo_deadlift", label: "KB Sumo Deadlift" },
  { key: "db_sumo_squat", label: "Dumbbell Sumo Squat" },
  { key: "ball_squat", label: "Ball Squat" },
  { key: "wall_sit", label: "Wall Sit" },
  { key: "thruster", label: "Thruster" },
  { key: "db_thruster", label: "Dumbbell Thruster" },
  { key: "kb_thruster", label: "Kettlebell Thruster" },
  { key: "man_maker", label: "Man Maker" },
  { key: "devil_press", label: "Devil Press" },
  { key: "clean_and_press", label: "Clean and Press" },
  { key: "db_clean", label: "Dumbbell Clean" },
  { key: "db_snatch", label: "Dumbbell Snatch" },
  { key: "single_arm_snatch", label: "Single Arm Snatch" },
  { key: "alternating_db_snatch", label: "Alternating DB Snatch" },
  { key: "windmill", label: "Windmill" },
  { key: "bent_press", label: "Bent Press" },
  { key: "side_press", label: "Side Press" },
  { key: "see_saw_press", label: "See Saw Press" },
  { key: "double_clean", label: "Double KB Clean" },
  { key: "double_snatch", label: "Double KB Snatch" },
  { key: "long_cycle", label: "Long Cycle" },
  { key: "jerk", label: "Jerk" },
  { key: "power_jerk", label: "Power Jerk" },
  { key: "squat_jerk", label: "Squat Jerk" },
  { key: "push_jerk_from_rack", label: "Push Jerk from Rack" },
  { key: "split_jerk_from_rack", label: "Split Jerk from Rack" },
  { key: "hang_power_clean", label: "Hang Power Clean" },
  { key: "hang_squat_clean", label: "Hang Squat Clean" },
  { key: "hang_power_snatch", label: "Hang Power Snatch" },
  { key: "hang_squat_snatch", label: "Hang Squat Snatch" },
  { key: "clean_from_blocks", label: "Clean from Blocks" },
  { key: "snatch_from_blocks", label: "Snatch from Blocks" },
  { key: "pull_from_blocks", label: "Pull from Blocks" },
  { key: "rdl_clean_pull", label: "RDL Clean Pull" },
  { key: "rdl_snatch_pull", label: "RDL Snatch Pull" },
  { key: "muscle_snatch", label: "Muscle Snatch" },
  { key: "power_clean_from_floor", label: "Power Clean (floor)" },
  { key: "squat_clean_from_floor", label: "Squat Clean (floor)" },
  { key: "snatch_pull_high", label: "High Snatch Pull" },
  { key: "clean_pull_high", label: "High Clean Pull" },
  { key: "pause_clean", label: "Pause Clean" },
  { key: "pause_snatch", label: "Pause Snatch" },
  { key: "tall_clean", label: "Tall Clean" },
  { key: "tall_snatch", label: "Tall Snatch" },
  { key: "drop_clean", label: "Drop Clean" },
  { key: "floating_clean", label: "Floating Clean" },
  { key: "segment_clean", label: "Segment Clean" },
  { key: "segment_snatch", label: "Segment Snatch" },
  { key: "pull_clean", label: "Pull + Clean" },
  { key: "pull_snatch", label: "Pull + Snatch" },
  { key: "jerk_dip", label: "Jerk Dip" },
  { key: "jerk_drive", label: "Jerk Drive" },
  { key: "push_press_from_rack", label: "Push Press from Rack" },
  { key: "strict_press_from_rack", label: "Strict Press from Rack" },
  { key: "bench_press_pause", label: "Pause Bench Press" },
  { key: "bench_press_2ct_pause", label: "2-Count Pause Bench" },
  { key: "spoto_bench", label: "Spoto Bench Press" },
  { key: "pin_bench", label: "Pin Bench Press" },
  { key: "floor_bench", label: "Floor Bench Press" },
  { key: "reverse_band_bench", label: "Reverse Band Bench" },
  { key: "slingshot_bench", label: "Slingshot Bench" },
  { key: "chain_bench", label: "Bench with Chains" },
  { key: "competition_bench", label: "Competition Bench" },
  { key: "wide_grip_bench", label: "Wide Grip Bench" },
  { key: "narrow_grip_bench", label: "Narrow Grip Bench" },
  { key: "cgb_bench", label: "Close Grip Bench" },
  { key: "incline_cgb", label: "Incline Close Grip Bench" },
  { key: "jm_bench", label: "JM Press (bench)" },
  { key: "skull_crusher_ez", label: "EZ Bar Skull Crusher" },
  { key: "skull_crusher_db", label: "Dumbbell Skull Crusher" },
  { key: "french_press", label: "French Press" },
  { key: "nosebreaker", label: "Nosebreaker" },
  { key: "tate_press", label: "Tate Press" },
  { key: "kickback", label: "Tricep Kickback" },
  { key: "overhead_cable_extension", label: "Overhead Cable Extension" },
  { key: "rope_pushdown", label: "Rope Pushdown" },
  { key: "v_bar_pushdown", label: "V-Bar Pushdown" },
  { key: "straight_bar_pushdown", label: "Straight Bar Pushdown" },
  { key: "single_arm_pushdown", label: "Single Arm Pushdown" },
  { key: "reverse_grip_pushdown", label: "Reverse Grip Pushdown" },
  { key: "dip_weighted", label: "Weighted Dip" },
  { key: "bench_dip_weighted", label: "Weighted Bench Dip" },
  { key: "diamond_dip", label: "Diamond Dip" },
  { key: "ring_dip_weighted", label: "Weighted Ring Dip" },
  { key: "curl_bar_ez", label: "EZ Bar Curl" },
  { key: "curl_bar_straight", label: "Straight Bar Curl" },
  { key: "curl_cable_straight", label: "Cable Straight Bar Curl" },
  { key: "curl_cable_rope", label: "Cable Rope Curl" },
  { key: "curl_incline_db", label: "Incline Dumbbell Curl" },
  { key: "curl_concentration", label: "Concentration Curl" },
  { key: "curl_spider", label: "Spider Curl" },
  { key: "curl_drag", label: "Drag Curl" },
  { key: "curl_reverse", label: "Reverse Curl" },
  { key: "curl_hammer", label: "Hammer Curl" },
  { key: "curl_cross_body", label: "Cross Body Hammer Curl" },
  { key: "curl_zottman", label: "Zottman Curl" },
  { key: "curl_21s", label: "21s Curl" },
  { key: "curl_preacher", label: "Preacher Curl" },
  { key: "curl_scott", label: "Scott Curl" },
  { key: "row_barbell_bent", label: "Bent Over Barbell Row" },
  { key: "row_barbell_yates", label: "Yates Row" },
  { key: "row_barbell_pendlay", label: "Pendlay Row" },
  { key: "row_tbar", label: "T-Bar Row" },
  { key: "row_tbar_close", label: "Close Grip T-Bar Row" },
  { key: "row_tbar_wide", label: "Wide Grip T-Bar Row" },
  { key: "row_chest_supported", label: "Chest Supported Row" },
  { key: "row_chest_supported_incline", label: "Incline Chest Supported Row" },
  { key: "row_dumbbell_one_arm", label: "One Arm Dumbbell Row" },
  { key: "row_dumbbell_bent", label: "Bent Over Two Arm Row" },
  { key: "row_cable_seated", label: "Seated Cable Row" },
  { key: "row_cable_straight_arm", label: "Straight Arm Cable Row" },
  { key: "row_landmine", label: "Landmine Row" },
  { key: "row_meadows", label: "Meadows Row" },
  { key: "row_machine", label: "Machine Row" },
  { key: "row_machine_chest_supported", label: "Chest Supported Machine Row" },
  { key: "row_inverted", label: "Inverted Row" },
  { key: "row_ring", label: "Ring Row" },
  { key: "row_trx", label: "TRX Row" },
  { key: "pull_up", label: "Pull-Up" },
  { key: "pull_up_weighted", label: "Weighted Pull-Up" },
  { key: "pull_up_wide_grip", label: "Wide Grip Pull-Up" },
  { key: "pull_up_close_grip", label: "Close Grip Pull-Up" },
  { key: "pull_up_neutral", label: "Neutral Grip Pull-Up" },
  { key: "pull_up_commando", label: "Commando Pull-Up" },
  { key: "pull_up_archer", label: "Archer Pull-Up" },
  { key: "pull_up_typewriter", label: "Typewriter Pull-Up" },
  { key: "chin_up_weighted", label: "Weighted Chin-Up" },
  { key: "chin_up_assisted", label: "Assisted Chin-Up" },
  { key: "lat_pulldown_wide", label: "Wide Grip Lat Pulldown" },
  { key: "lat_pulldown_close", label: "Close Grip Lat Pulldown" },
  { key: "lat_pulldown_reverse", label: "Reverse Grip Lat Pulldown" },
  { key: "lat_pulldown_neutral", label: "Neutral Lat Pulldown" },
  { key: "lat_pulldown_single_arm", label: "Single Arm Lat Pulldown" },
  { key: "lat_pulldown_straight_arm", label: "Straight Arm Pulldown" },
  { key: "pullover_cable", label: "Cable Pullover" },
  { key: "pullover_dumbbell", label: "Dumbbell Pullover" },
  { key: "pullover_machine", label: "Machine Pullover" },
  { key: "muscle_up_weighted", label: "Weighted Muscle-Up" },
  { key: "muscle_up_strict", label: "Strict Muscle-Up" },
  { key: "muscle_up_kipping", label: "Kipping Muscle-Up" },
  { key: "front_lever", label: "Front Lever" },
  { key: "back_lever", label: "Back Lever" },
  { key: "planche", label: "Planche" },
  { key: "l_sit", label: "L-Sit" },
  { key: "hollow_hold", label: "Hollow Hold" },
  { key: "arch_hold", label: "Arch Hold" },
  { key: "ab_crunch", label: "Ab Crunch" },
  { key: "cable_crunch", label: "Cable Crunch" },
  { key: "decline_crunch", label: "Decline Crunch" },
  { key: "bicycle_crunch", label: "Bicycle Crunch" },
  { key: "russian_twist", label: "Russian Twist" },
  { key: "wood_chop", label: "Wood Chop" },
  { key: "pallof_hold", label: "Pallof Hold" },
  { key: "side_plank", label: "Side Plank" },
  { key: "dead_bug_weighted", label: "Weighted Dead Bug" },
  { key: "v_up", label: "V-Up" },
  { key: "toe_touch", label: "Toe Touch" },
  { key: "leg_raise_hanging", label: "Hanging Leg Raise" },
  { key: "leg_raise_lying", label: "Lying Leg Raise" },
  { key: "leg_raise_captain", label: "Captain's Chair Leg Raise" },
  { key: "reverse_crunch", label: "Reverse Crunch" },
  { key: "flutter_kick", label: "Flutter Kick" },
  { key: "scissor_kick", label: "Scissor Kick" },
  { key: "mountain_climber", label: "Mountain Climber" },
  { key: "bear_crawl", label: "Bear Crawl" },
  { key: "bird_dog", label: "Bird Dog" },
  { key: "superman", label: "Superman" },
  { key: "reverse_hyperextension", label: "Reverse Hyperextension" },
  { key: "back_extension_weighted", label: "Weighted Back Extension" },
  { key: "ghr_sit_up", label: "GHR Sit-Up" },
  { key: "sit_up", label: "Sit-Up" },
  { key: "weighted_sit_up", label: "Weighted Sit-Up" },
  { key: "medicine_ball_slam", label: "Medicine Ball Slam" },
  { key: "medicine_ball_throw", label: "Medicine Ball Throw" },
  { key: "medicine_ball_chest_pass", label: "Medicine Ball Chest Pass" },
  { key: "medicine_ball_rotational_throw", label: "Med Ball Rotational Throw" },
  { key: "wall_ball", label: "Wall Ball" },
  { key: "thruster_barbell", label: "Barbell Thruster" },
  { key: "thruster_dumbbell", label: "Dumbbell Thruster" },
  { key: "thruster_kettlebell", label: "Kettlebell Thruster" },
  { key: "cluster", label: "Cluster" },
  { key: "power_clean_thruster", label: "Power Clean + Thruster" },
];

/** Cardiovascular — running, rowing, bike, swim, etc. */
export const CARDIO_OPTIONS: BenchmarkOption[] = [
  { key: "MAS", label: "MAS (m/s)", unit: "m/s" },
  { key: "vo2max", label: "VO₂ max (ml/kg/min)", unit: "ml/kg/min" },
  { key: "vt1", label: "VT1 (bpm or pace)", unit: "" },
  { key: "vt2", label: "VT2 (bpm or pace)", unit: "" },
  { key: "two_mile_time", label: "2 Mile Time (sec)", unit: "sec" },
  { key: "five_k_time", label: "5K Time (sec)", unit: "sec" },
  { key: "ten_k_time", label: "10K Time (sec)", unit: "sec" },
  { key: "half_marathon_time", label: "Half Marathon (sec)", unit: "sec" },
  { key: "marathon_time", label: "Marathon (sec)", unit: "sec" },
  { key: "row_2k", label: "2K Row (sec)", unit: "sec" },
  { key: "row_5k", label: "5K Row (sec)", unit: "sec" },
  { key: "bike_ftp", label: "FTP (watts)", unit: "W" },
  { key: "swim_400", label: "400 m Swim (sec)", unit: "sec" },
  { key: "one_mile_time", label: "1 Mile Time (sec)", unit: "sec" },
  { key: "three_k_time", label: "3K Time (sec)", unit: "sec" },
  { key: "fifteen_k_time", label: "15K Time (sec)", unit: "sec" },
  { key: "twenty_k_time", label: "20K Time (sec)", unit: "sec" },
  { key: "row_500", label: "500 m Row (sec)", unit: "sec" },
  { key: "row_1k", label: "1K Row (sec)", unit: "sec" },
  { key: "row_6k", label: "6K Row (sec)", unit: "sec" },
  { key: "row_10k", label: "10K Row (sec)", unit: "sec" },
  { key: "row_21k", label: "Half Marathon Row (sec)", unit: "sec" },
  { key: "row_42k", label: "Marathon Row (sec)", unit: "sec" },
  { key: "swim_50", label: "50 m Swim (sec)", unit: "sec" },
  { key: "swim_100", label: "100 m Swim (sec)", unit: "sec" },
  { key: "swim_200", label: "200 m Swim (sec)", unit: "sec" },
  { key: "swim_800", label: "800 m Swim (sec)", unit: "sec" },
  { key: "swim_1500", label: "1500 m Swim (sec)", unit: "sec" },
  { key: "bike_1min", label: "1 min Bike (kJ)", unit: "kJ" },
  { key: "bike_5min", label: "5 min Bike (kJ)", unit: "kJ" },
  { key: "bike_20min", label: "20 min Bike (watts)", unit: "W" },
  { key: "bike_60min", label: "60 min Bike (watts)", unit: "W" },
  { key: "run_100m", label: "100 m Run (sec)", unit: "sec" },
  { key: "run_200m", label: "200 m Run (sec)", unit: "sec" },
  { key: "run_400m", label: "400 m Run (sec)", unit: "sec" },
  { key: "run_800m", label: "800 m Run (sec)", unit: "sec" },
  { key: "run_1500m", label: "1500 m Run (sec)", unit: "sec" },
  { key: "run_3k", label: "3K Run (sec)", unit: "sec" },
  { key: "run_5k", label: "5K Run (sec)", unit: "sec" },
  { key: "run_10k", label: "10K Run (sec)", unit: "sec" },
  { key: "run_half", label: "Half Marathon (sec)", unit: "sec" },
  { key: "run_marathon", label: "Marathon (sec)", unit: "sec" },
  { key: "ski_500", label: "500 m Ski (sec)", unit: "sec" },
  { key: "ski_1k", label: "1K Ski (sec)", unit: "sec" },
  { key: "ski_2k", label: "2K Ski (sec)", unit: "sec" },
  { key: "ski_5k", label: "5K Ski (sec)", unit: "sec" },
  { key: "assault_bike_1min", label: "Assault Bike 1 min (cal)", unit: "cal" },
  { key: "assault_bike_4min", label: "Assault Bike 4 min (cal)", unit: "cal" },
  { key: "assault_bike_10min", label: "Assault Bike 10 min (cal)", unit: "cal" },
  { key: "echo_bike_1min", label: "Echo Bike 1 min (cal)", unit: "cal" },
  { key: "echo_bike_4min", label: "Echo Bike 4 min (cal)", unit: "cal" },
  { key: "concept2_bike_1min", label: "C2 Bike 1 min (kJ)", unit: "kJ" },
  { key: "concept2_bike_4min", label: "C2 Bike 4 min (kJ)", unit: "kJ" },
  { key: "rhr", label: "Resting Heart Rate (bpm)", unit: "bpm" },
  { key: "max_hr", label: "Max Heart Rate (bpm)", unit: "bpm" },
  { key: "lactate_threshold_hr", label: "Lactate Threshold HR (bpm)", unit: "bpm" },
  { key: "critical_power_run", label: "Critical Power Run (m/s)", unit: "m/s" },
  { key: "critical_power_bike", label: "Critical Power Bike (W)", unit: "W" },
  { key: "anaerobic_capacity_run", label: "Anaerobic Capacity Run (m/s)", unit: "m/s" },
  { key: "cooper_test", label: "Cooper Test (m in 12 min)", unit: "m" },
  { key: "one_five_test", label: "1.5 Mile Test (sec)", unit: "sec" },
  { key: "beep_test", label: "Beep Test (level)", unit: "" },
  { key: "yo_yo_ir1", label: "Yo-Yo IR1 (m)", unit: "m" },
  { key: "yo_yo_ir2", label: "Yo-Yo IR2 (m)", unit: "m" },
  { key: "step_test", label: "Step Test (recovery bpm)", unit: "bpm" },
  { key: "rockport_walk", label: "Rockport Walk Test (VO2 estimate)", unit: "" },
  { key: "treadmill_vo2", label: "Treadmill VO2 (ml/kg/min)", unit: "ml/kg/min" },
  { key: "bike_vo2", label: "Bike VO2 (ml/kg/min)", unit: "ml/kg/min" },
  { key: "swim_vo2", label: "Swim VO2 (ml/kg/min)", unit: "ml/kg/min" },
  { key: "pace_zone2", label: "Zone 2 Pace (min/km)", unit: "min/km" },
  { key: "pace_zone3", label: "Zone 3 Pace (min/km)", unit: "min/km" },
  { key: "pace_zone4", label: "Zone 4 Pace (min/km)", unit: "min/km" },
  { key: "pace_zone5", label: "Zone 5 Pace (min/km)", unit: "min/km" },
  { key: "cycling_zone2", label: "Zone 2 Power (W)", unit: "W" },
  { key: "cycling_zone3", label: "Zone 3 Power (W)", unit: "W" },
  { key: "cycling_zone4", label: "Zone 4 Power (W)", unit: "W" },
  { key: "cycling_zone5", label: "Zone 5 Power (W)", unit: "W" },
  { key: "rowing_split_2k", label: "2K Split (min/500m)", unit: "min/500m" },
  { key: "rowing_split_5k", label: "5K Split (min/500m)", unit: "min/500m" },
  { key: "swim_pace_100", label: "100 m Swim Pace (sec)", unit: "sec" },
  { key: "swim_pace_400", label: "400 m Swim Pace (sec)", unit: "sec" },
  { key: "elliptical_vo2", label: "Elliptical VO2 (ml/kg/min)", unit: "ml/kg/min" },
  { key: "stair_climb_1min", label: "1 min Stair Climb (floors)", unit: "" },
  { key: "stair_climb_4min", label: "4 min Stair Climb (floors)", unit: "" },
  { key: "hiking_vert", label: "Hiking Vertical (m)", unit: "m" },
  { key: "time_trial_20k_bike", label: "20K Bike TT (sec)", unit: "sec" },
  { key: "time_trial_40k_bike", label: "40K Bike TT (sec)", unit: "sec" },
  { key: "triathlon_sprint_swim", label: "Sprint Tri Swim (sec)", unit: "sec" },
  { key: "triathlon_sprint_bike", label: "Sprint Tri Bike (sec)", unit: "sec" },
  { key: "triathlon_sprint_run", label: "Sprint Tri Run (sec)", unit: "sec" },
  { key: "triathlon_olympic_swim", label: "Olympic Tri Swim (sec)", unit: "sec" },
  { key: "triathlon_olympic_bike", label: "Olympic Tri Bike (sec)", unit: "sec" },
  { key: "triathlon_olympic_run", label: "Olympic Tri Run (sec)", unit: "sec" },
  { key: "triathlon_half_swim", label: "Half Iron Swim (sec)", unit: "sec" },
  { key: "triathlon_half_bike", label: "Half Iron Bike (sec)", unit: "sec" },
  { key: "triathlon_half_run", label: "Half Iron Run (sec)", unit: "sec" },
  { key: "triathlon_iron_swim", label: "Ironman Swim (sec)", unit: "sec" },
  { key: "triathlon_iron_bike", label: "Ironman Bike (sec)", unit: "sec" },
  { key: "triathlon_iron_run", label: "Ironman Run (sec)", unit: "sec" },
  { key: "duathlon_run1", label: "Duathlon Run 1 (sec)", unit: "sec" },
  { key: "duathlon_bike", label: "Duathlon Bike (sec)", unit: "sec" },
  { key: "duathlon_run2", label: "Duathlon Run 2 (sec)", unit: "sec" },
  { key: "aquathon_swim", label: "Aquathon Swim (sec)", unit: "sec" },
  { key: "aquathon_run", label: "Aquathon Run (sec)", unit: "sec" },
  { key: "open_water_1k", label: "Open Water 1K (sec)", unit: "sec" },
  { key: "open_water_2k", label: "Open Water 2K (sec)", unit: "sec" },
  { key: "open_water_5k", label: "Open Water 5K (sec)", unit: "sec" },
  { key: "pool_100_back", label: "100 m Backstroke (sec)", unit: "sec" },
  { key: "pool_100_breast", label: "100 m Breaststroke (sec)", unit: "sec" },
  { key: "pool_100_fly", label: "100 m Butterfly (sec)", unit: "sec" },
  { key: "pool_200_im", label: "200 m IM (sec)", unit: "sec" },
  { key: "pool_400_im", label: "400 m IM (sec)", unit: "sec" },
  { key: "indoor_row_1min", label: "1 min Row (m)", unit: "m" },
  { key: "indoor_row_4min", label: "4 min Row (m)", unit: "m" },
  { key: "indoor_row_30min", label: "30 min Row (m)", unit: "m" },
  { key: "indoor_row_60min", label: "60 min Row (m)", unit: "m" },
  { key: "running_economy", label: "Running Economy (ml/kg/km)", unit: "" },
  { key: "cycling_efficiency", label: "Cycling Efficiency (%)", unit: "%" },
  { key: "swim_eff", label: "Swim Efficiency (SWOLF)", unit: "" },
  { key: "hr_z1_upper", label: "Z1 Upper (bpm)", unit: "bpm" },
  { key: "hr_z2_lower", label: "Z2 Lower (bpm)", unit: "bpm" },
  { key: "hr_z2_upper", label: "Z2 Upper (bpm)", unit: "bpm" },
  { key: "hr_z3_lower", label: "Z3 Lower (bpm)", unit: "bpm" },
  { key: "hr_z3_upper", label: "Z3 Upper (bpm)", unit: "bpm" },
  { key: "hr_z4_lower", label: "Z4 Lower (bpm)", unit: "bpm" },
  { key: "hr_z4_upper", label: "Z4 Upper (bpm)", unit: "bpm" },
  { key: "hr_z5_lower", label: "Z5 Lower (bpm)", unit: "bpm" },
  { key: "power_z2_lower", label: "Power Z2 Lower (W)", unit: "W" },
  { key: "power_z2_upper", label: "Power Z2 Upper (W)", unit: "W" },
  { key: "power_z3_lower", label: "Power Z3 Lower (W)", unit: "W" },
  { key: "power_z3_upper", label: "Power Z3 Upper (W)", unit: "W" },
  { key: "power_z4_lower", label: "Power Z4 Lower (W)", unit: "W" },
  { key: "power_z4_upper", label: "Power Z4 Upper (W)", unit: "W" },
  { key: "power_z5_lower", label: "Power Z5 Lower (W)", unit: "W" },
  { key: "power_z5_upper", label: "Power Z5 Upper (W)", unit: "W" },
];

/** Power & speed — jumps, sprints, throws */
export const POWER_OPTIONS: BenchmarkOption[] = [
  { key: "CMJ", label: "Countermovement Jump (cm)", unit: "cm" },
  { key: "SJ", label: "Squat Jump (cm)", unit: "cm" },
  { key: "RSI", label: "RSI (reactive strength)", unit: "" },
  { key: "sprint_10m", label: "10 m Sprint (sec)", unit: "sec" },
  { key: "sprint_20m", label: "20 m Sprint (sec)", unit: "sec" },
  { key: "sprint_30m", label: "30 m Sprint (sec)", unit: "sec" },
  { key: "broad_jump", label: "Broad Jump (cm)", unit: "cm" },
  { key: "med_ball_throw", label: "Med Ball Throw (m)", unit: "m" },
  { key: "sprint_40m", label: "40 m Sprint (sec)", unit: "sec" },
  { key: "sprint_60m", label: "60 m Sprint (sec)", unit: "sec" },
  { key: "sprint_100m", label: "100 m Sprint (sec)", unit: "sec" },
  { key: "sprint_200m", label: "200 m Sprint (sec)", unit: "sec" },
  { key: "flying_10m", label: "Flying 10 m (sec)", unit: "sec" },
  { key: "flying_20m", label: "Flying 20 m (sec)", unit: "sec" },
  { key: "flying_30m", label: "Flying 30 m (sec)", unit: "sec" },
  { key: "standing_long_jump", label: "Standing Long Jump (cm)", unit: "cm" },
  { key: "triple_jump", label: "Triple Jump (m)", unit: "m" },
  { key: "vertical_jump", label: "Vertical Jump (cm)", unit: "cm" },
  { key: "drop_jump", label: "Drop Jump (cm)", unit: "cm" },
  { key: "single_leg_cmj", label: "Single Leg CMJ (cm)", unit: "cm" },
  { key: "single_leg_sj", label: "Single Leg Squat Jump (cm)", unit: "cm" },
  { key: "alternate_leg_bound", label: "Alternate Leg Bound (m)", unit: "m" },
  { key: "single_leg_bound", label: "Single Leg Bound (m)", unit: "m" },
  { key: "triple_hop", label: "Triple Hop (m)", unit: "m" },
  { key: "cross_over_hop", label: "Crossover Hop (m)", unit: "m" },
  { key: "med_ball_chest_throw", label: "Med Ball Chest Pass (m)", unit: "m" },
  { key: "med_ball_overhead_throw", label: "Med Ball Overhead Throw (m)", unit: "m" },
  { key: "med_ball_rotational_throw", label: "Med Ball Rotational Throw (m)", unit: "m" },
  { key: "med_ball_slam", label: "Med Ball Slam (height/cm)", unit: "cm" },
  { key: "med_ball_2kg_throw", label: "2 kg Med Ball Throw (m)", unit: "m" },
  { key: "med_ball_3kg_throw", label: "3 kg Med Ball Throw (m)", unit: "m" },
  { key: "med_ball_4kg_throw", label: "4 kg Med Ball Throw (m)", unit: "m" },
  { key: "med_ball_5kg_throw", label: "5 kg Med Ball Throw (m)", unit: "m" },
  { key: "box_jump", label: "Box Jump (cm)", unit: "cm" },
  { key: "depth_jump", label: "Depth Jump (cm)", unit: "cm" },
  { key: "reactive_strength_index", label: "Reactive Strength Index", unit: "" },
  { key: "contact_time", label: "Contact Time (ms)", unit: "ms" },
  { key: "flight_time", label: "Flight Time (ms)", unit: "ms" },
  { key: "peak_force_cmj", label: "Peak Force CMJ (N)", unit: "N" },
  { key: "peak_power_cmj", label: "Peak Power CMJ (W)", unit: "W" },
  { key: "peak_velocity_cmj", label: "Peak Velocity CMJ (m/s)", unit: "m/s" },
  { key: "impulse", label: "Impulse (Ns)", unit: "Ns" },
  { key: "acceleration_0_10m", label: "Acceleration 0–10 m (sec)", unit: "sec" },
  { key: "acceleration_0_20m", label: "Acceleration 0–20 m (sec)", unit: "sec" },
  { key: "acceleration_0_30m", label: "Acceleration 0–30 m (sec)", unit: "sec" },
  { key: "max_velocity", label: "Max Velocity (m/s)", unit: "m/s" },
  { key: "agility_t_test", label: "T-Test (sec)", unit: "sec" },
  { key: "agility_505", label: "505 Agility (sec)", unit: "sec" },
  { key: "agility_pro", label: "Pro Agility (sec)", unit: "sec" },
  { key: "agility_3cone", label: "3-Cone Drill (sec)", unit: "sec" },
  { key: "agility_illinois", label: "Illinois Agility (sec)", unit: "sec" },
  { key: "agility_arrowhead", label: "Arrowhead Agility (sec)", unit: "sec" },
  { key: "change_of_direction", label: "Change of Direction (sec)", unit: "sec" },
  { key: "zigzag_run", label: "Zigzag Run (sec)", unit: "sec" },
  { key: "hexagon_test", label: "Hexagon Test (sec)", unit: "sec" },
  { key: "lateral_jump", label: "Lateral Jump (cm)", unit: "cm" },
  { key: "lateral_bound", label: "Lateral Bound (m)", unit: "m" },
  { key: "single_leg_hop", label: "Single Leg Hop (cm)", unit: "cm" },
  { key: "single_leg_triple_hop", label: "Single Leg Triple Hop (m)", unit: "m" },
  { key: "ankle_stiffness", label: "Ankle Stiffness (kN/m)", unit: "kN/m" },
  { key: "eccentric_utilization", label: "Eccentric Utilization Ratio", unit: "" },
  { key: "bounce_drop_jump", label: "Bounce Drop Jump (cm)", unit: "cm" },
  { key: "countermovement_rebound", label: "Countermovement Rebound (cm)", unit: "cm" },
  { key: "stiffness", label: "Leg Stiffness (kN/m)", unit: "kN/m" },
  { key: "power_clean_1rm", label: "Power Clean 1RM (kg)", unit: "kg" },
  { key: "hang_clean_1rm", label: "Hang Clean 1RM (kg)", unit: "kg" },
  { key: "push_jerk_1rm", label: "Push Jerk 1RM (kg)", unit: "kg" },
  { key: "jump_squat_30", label: "Jump Squat 30% (cm)", unit: "cm" },
  { key: "jump_squat_50", label: "Jump Squat 50% (cm)", unit: "cm" },
  { key: "jump_squat_0", label: "Jump Squat Unloaded (cm)", unit: "cm" },
  { key: "weighted_jump_squat", label: "Weighted Jump Squat (kg)", unit: "kg" },
  { key: "loaded_cmj", label: "Loaded CMJ (kg)", unit: "kg" },
  { key: "isometric_mid_thigh_pull", label: "Isometric Mid-Thigh Pull (N)", unit: "N" },
  { key: "isometric_leg_press", label: "Isometric Leg Press (N)", unit: "N" },
  { key: "rate_of_force_dev", label: "Rate of Force Development (N/s)", unit: "N/s" },
  { key: "time_to_peak_force", label: "Time to Peak Force (ms)", unit: "ms" },
  { key: "peak_force_isometric", label: "Peak Force Isometric (N)", unit: "N" },
  { key: "bench_throw", label: "Bench Throw (m)", unit: "m" },
  { key: "bench_throw_30", label: "Bench Throw 30% (m)", unit: "m" },
  { key: "bench_throw_50", label: "Bench Throw 50% (m)", unit: "m" },
  { key: "seated_shot_put", label: "Seated Shot Put (m)", unit: "m" },
  { key: "standing_shot_put", label: "Standing Shot Put (m)", unit: "m" },
  { key: "overhead_shot_put", label: "Overhead Shot Put (m)", unit: "m" },
  { key: "backward_throw", label: "Backward Overhead Throw (m)", unit: "m" },
  { key: "sprint_fatigue", label: "Sprint Fatigue Index (%)", unit: "%" },
  { key: "repeat_sprint_ability", label: "Repeat Sprint Ability (sec)", unit: "sec" },
  { key: "yo_yo_ie2", label: "Yo-Yo IE2 (m)", unit: "m" },
  { key: "running_anaerobic", label: "Running Anaerobic Test (m)", unit: "m" },
  { key: "wingate_5", label: "Wingate 5 s (W)", unit: "W" },
  { key: "wingate_30", label: "Wingate 30 s (W)", unit: "W" },
  { key: "wingate_peak", label: "Wingate Peak Power (W)", unit: "W" },
  { key: "wingate_mean", label: "Wingate Mean Power (W)", unit: "W" },
  { key: "cycling_sprint_5s", label: "5 s Cycling Sprint (W)", unit: "W" },
  { key: "cycling_sprint_10s", label: "10 s Cycling Sprint (W)", unit: "W" },
  { key: "rowing_sprint_1min", label: "1 min Rowing Sprint (m)", unit: "m" },
  { key: "rowing_sprint_500m", label: "500 m Row Sprint (sec)", unit: "sec" },
];

/** All options by section id for dropdowns */
export const OPTIONS_BY_SECTION: Record<string, BenchmarkOption[]> = {
  strength: STRENGTH_OPTIONS,
  cardiovascular: CARDIO_OPTIONS,
  power: POWER_OPTIONS,
};

/** Build display name map for all options (for dashboard etc.) */
export const ALL_OPTION_DISPLAY_NAMES: Record<string, string> = Object.fromEntries(
  [...STRENGTH_OPTIONS, ...CARDIO_OPTIONS, ...POWER_OPTIONS].map((e) => [e.key, e.label])
);
