/**
 * Programme Generation Engine — inputs and periodisation models.
 * Programmes generated by AI using capacity profile, goal, timeline, equipment, history, readiness, injury flags.
 */

import type { CapacityProfile } from "./capacity";
import type { EquipmentEnvironment } from "./equipment";

export const PERIODISATION_MODELS = [
  "block_periodisation",
  "undulating_periodisation",
  "concurrent_model",
  "conjugate_hybrid",
] as const;

export type PeriodisationModel = (typeof PERIODISATION_MODELS)[number];

export type ProgrammeGenerationInput = {
  capacityProfile: CapacityProfile;
  goal: string;
  goalTimelineWeeks: number;
  equipment: EquipmentEnvironment;
  trainingHistorySummary?: string;
  readinessTrend?: "improving" | "stable" | "declining";
  injuryOrPainFlags?: string[];
};

export type ProgrammeGenerationResult = {
  periodisationModel: PeriodisationModel;
  blockLengthWeeks: number;
  programmeSummary: string;
};

export const PERIODISATION_LABELS: Record<PeriodisationModel, string> = {
  block_periodisation: "Block Periodisation",
  undulating_periodisation: "Undulating Periodisation",
  concurrent_model: "Concurrent Model",
  conjugate_hybrid: "Conjugate Hybrid",
};
